/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Item } from "./types";
export namespace Components {
    interface AppImport {
    }
    interface AppMain {
        "items": Item[];
        "randomBounds": { counts: { lower: number, upper: number }, weights: { lower: number, upper: number }, values: { lower: number, upper: number }, count: number };
    }
    interface AppRandom {
        "count": number;
        "counts": { lower: number, upper: number };
        "values": { lower: number, upper: number };
        "weights": { lower: number, upper: number };
    }
}
declare global {
    interface HTMLAppImportElement extends Components.AppImport, HTMLStencilElement {
    }
    var HTMLAppImportElement: {
        prototype: HTMLAppImportElement;
        new (): HTMLAppImportElement;
    };
    interface HTMLAppMainElement extends Components.AppMain, HTMLStencilElement {
    }
    var HTMLAppMainElement: {
        prototype: HTMLAppMainElement;
        new (): HTMLAppMainElement;
    };
    interface HTMLAppRandomElement extends Components.AppRandom, HTMLStencilElement {
    }
    var HTMLAppRandomElement: {
        prototype: HTMLAppRandomElement;
        new (): HTMLAppRandomElement;
    };
    interface HTMLElementTagNameMap {
        "app-import": HTMLAppImportElement;
        "app-main": HTMLAppMainElement;
        "app-random": HTMLAppRandomElement;
    }
}
declare namespace LocalJSX {
    interface AppImport {
    }
    interface AppMain {
        "items"?: Item[];
        "randomBounds"?: { counts: { lower: number, upper: number }, weights: { lower: number, upper: number }, values: { lower: number, upper: number }, count: number };
    }
    interface AppRandom {
        "count"?: number;
        "counts"?: { lower: number, upper: number };
        "values"?: { lower: number, upper: number };
        "weights"?: { lower: number, upper: number };
    }
    interface IntrinsicElements {
        "app-import": AppImport;
        "app-main": AppMain;
        "app-random": AppRandom;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-import": LocalJSX.AppImport & JSXBase.HTMLAttributes<HTMLAppImportElement>;
            "app-main": LocalJSX.AppMain & JSXBase.HTMLAttributes<HTMLAppMainElement>;
            "app-random": LocalJSX.AppRandom & JSXBase.HTMLAttributes<HTMLAppRandomElement>;
        }
    }
}
